//Request

//include
#include "SystemDisplay.h"
#include <math.h>

//function
void Display_0(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_RESET);
}	

void Display_1(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_RESET);
}
void Display_2(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
void Display_3(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
void Display_4(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
void Display_5(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
void Display_6(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
void Display_7(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_RESET);
}
void Display_8(void)
{
		HAL_GPIO_WritePin(GPIOG, DIG1_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOC, DIG2_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, DIG3_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOC, DIG4_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, DIG5_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, DIG6_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOE, C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOF, D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOG, G_Pin, GPIO_PIN_SET);
}
